### ISSUE TITLE
Very similar website/project!

### ISSUE THREAD

**Issue by Venryx** [GruffDebate/server#13]
Hey there, I noticed your link to this project from the "Democracy Earth" slack, and read through some of the source code. Your project appears to be very similar to one I've been building myself for the last few months!

Repo: https://github.com/Venryx/DebateMap
Website: https://debatemap.live

The home page and "about" page contain some info on what I have planned; if it's close enough to your own, it would be cool to talk with you some about design of this type of website, and possibly collaborate on development in the future. There's a lot of decisions which need to be made which there aren't clear answers to yet, so combining our ideas into the same project might help us seek out that design faster.

**Comment by bigokro** [comment]
Hey! Thanks for the heads up! I'll take a look at what you're doing. For more back-and-forth conversation, it's probably best to do it in the Democracy Earth Slack, but for recording final decisions, it's good to have a record here in the project.
